version: "2.2"
services:
    chrome_headless:
      image: browserless/chrome

    web_proxy:
        # docker build -t insight .
        build: .
        # image: insight
        environment:
          NODE_ENV: prod
          BROWSERLESS_HOST: chrome_headless:3000
        ports:
            - 8080:8080